### PR TITLE
tag(0.4.0): hardtag

### PR DESCRIPTION
**Pull request by mfo**
for Monty Kosma ; 

```Hi! thanks for resque-restriction, I'm trying to set it up to work with ActiveJob in Rails 4.2.4. Can you guys tag the 0.4.0 release or update the gemspec so I can reference it in my Gemfile? hate having to pull off unversioned master.... ?```

flyerhzm ; can you release this version ?

### CODE REVIEW

**Comment by flyerhzm** [comment]
@mfo resque-restriction 0.4.0 is released, many thanks, btw, I don't have time for this project, do you consider take some time to maintain it?

**Comment by mfo** [comment]
No prob :-)

**Comment by flyerhzm** [comment]
@mfo I have added you as a collaborator, if you want to release a new version, just add you to gemspec, btw, I'd like to see using bundler instead of jeweler to release version, thanks.

**Comment by mfo** [comment]
Hi Richard,

I noticed that you released the last version unfortunately I assume that
because the gemspec reference the gem itself it can't be installed.

So I pushed an update to the .gempsec and added me in the authors Array.

Unfortunately I can't publish the gem myself... Any idea ?

Best,
Martin

On Tue, Oct 20, 2015 at 5:08 AM, Richard Huang <notifications@github.com>
wrote:

> @mfo <https://github.com/mfo> I have added you as a collaborator, if you
> want to release a new version, just add you to gemspec, btw, I'd like to
> see using bundler instead of jeweler to release version, thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flyerhzm/resque-restriction/pull/11#issuecomment-149414832>
> .
>



-- 
*Martin Fourcade*
*Customer Care Hero / Happy Geek / Founder at sharypic*
- Web: http://sharypic.com
- Mobile: +33 6 37 60 77 56
- Skype: martin.fourcade1
- Twitter: @mfourcade

**Comment by flyerhzm** [comment]
@mfo what's your email address? I will add it by gem command.

**Comment by mfo** [comment]
Hi Richard,

my email is fourcade.m@gmail.com.

Thanks a lot ;-)

On Mon, Nov 2, 2015 at 1:08 AM, Richard Huang <notifications@github.com>
wrote:

> @mfo <https://github.com/mfo> what's your email address? I will add it by
> gem command.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flyerhzm/resque-restriction/pull/11#issuecomment-152879595>
> .
>



-- 
*Martin Fourcade*
*Customer Care Hero / Happy Geek / Founder at sharypic*
- Web: http://sharypic.com
- Mobile: +33 6 37 60 77 56
- Skype: martin.fourcade1
- Twitter: @mfourcade

**Comment by flyerhzm** [comment]
@mfo ok, please try again.

**Comment by mfo** [comment]
Hi Richard ;

thanks it worked. I'll now work on the next release that fix the 'self
require'.

Best.

On Mon, Nov 2, 2015 at 9:30 AM, Richard Huang <notifications@github.com>
wrote:

> @mfo <https://github.com/mfo> ok, please try again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flyerhzm/resque-restriction/pull/11#issuecomment-152950658>
> .
>



-- 
*Martin Fourcade*
*Customer Care Hero / Happy Geek / Founder at sharypic*
- Web: http://sharypic.com
- Mobile: +33 6 37 60 77 56
- Skype: martin.fourcade1
- Twitter: @mfourcade

**Comment by flyerhzm** [comment]
@mfo good job, thanks.

**Comment by mfo** [comment]
tx for your help & patience.

May the force be with you.

On Mon, Nov 2, 2015 at 9:50 AM, Richard Huang <notifications@github.com>
wrote:

> @mfo <https://github.com/mfo> good job, thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flyerhzm/resque-restriction/pull/11#issuecomment-152957913>
> .
>



-- 
*Martin Fourcade*
*Customer Care Hero / Happy Geek / Founder at sharypic*
- Web: http://sharypic.com
- Mobile: +33 6 37 60 77 56
- Skype: martin.fourcade1
- Twitter: @mfourcade

**Pull request merged**
